# -*- coding: utf-8 -*-
"""HFamazon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MZncVnOHCmrmEbzKOl_LjgvsLcoMGX15
"""

!pip install datasets transformers huggingface_hub evaluate
!apt-get install git-lfs

import pandas as pd
from datasets import Dataset
from huggingface_hub import login

df = pd.read_csv("/content/drive/MyDrive/Amazon Review DL/cleaned_data.csv")
df

dataset = Dataset.from_pandas(df)

train_test_split=dataset.train_test_split(test_size=0.3)
test_valid_split=train_test_split["test"].train_test_split(test_size=0.5)

train_dataset=train_test_split["train"]
test_dataset=test_valid_split["test"]
valid_dataset=test_valid_split["train"]

from datasets import DatasetDict
dataset_dict=DatasetDict({
    "train":train_dataset,
    "test":test_dataset,
    "valid":valid_dataset
})

print(dataset_dict)

login()

preprocess_affr = "PRINCEEMMANUEL/PREPROCESS_AMAZON"
dataset_dict.push_to_hub(preprocess_affr)

from datasets import load_dataset
mnist = load_dataset("PRINCEEMMANUEL/PREPROCESS_AMAZON")

mnist

